-- =============================================
-- Script: Seed Admin User
-- Description: Insert default admin user for initial login
-- Author: System
-- Date: 2025-11-18
-- Password: Admin@123 (hashed with bcrypt)
-- =============================================

USE EvidenceManagementDB;
GO

-- Insert Admin User
-- Password: Admin@123
-- Bcrypt hash: $2b$10$rQZ5YvJ5kK5h5Z5Z5Z5Z5euN8K5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Zu
-- NOTE: This is a placeholder hash. The actual hash will be generated by the backend on first run.

SET IDENTITY_INSERT Users ON;

INSERT INTO Users (Id, Username, Email, PasswordHash, FirstName, LastName, RoleId, IsActive) VALUES
(1, 'admin', 'admin@evidence.com', '$2b$10$YourHashWillBeGeneratedByBackend', 'Admin', 'System', 1, 1);

SET IDENTITY_INSERT Users OFF;
GO

PRINT 'Admin user seeded successfully!';
PRINT 'Username: admin';
PRINT 'Email: admin@evidence.com';
PRINT 'Password: Admin@123 (Please change after first login)';
